postgres:
  image: "postgres:9.5"
  volumes_from:
    - data
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: gargantext
    POSTGRES_USER: gargantua
web:
  command: python manage.py runserver 0.0.0.0:8000
  build: .
  volumes:
      - .:/srv/
    ports:
      - "8000:8000"
    depends_on:
      - db
  build: .
  ports:
    - "3000:3000"
  links:
    - postgres
  volumes:
    - ../:/srv/
  volumes_from:
    - data
  environment:
    HOST: 0.0.0.0
    PORT: 3000
    
data:
  image: gargantext
  command: echo 'Data Container for PostgreSQL and Initial Data'
  volumes:
    - /var/lib/postgresql/data
    - /bundler
