postgres:
  image: "postgres:9.4"
  volumes_from:
    - data
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: gargantext
    POSTGRES_USER: gargantua
web:
  build: .
  ports:
    - "3000:3000"
  links:
    - postgres
  volumes:
    - ../:/app/
  volumes_from:
    - data
  environment:
    HOST: 0.0.0.0
    PORT: 3000
    
data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL and Bundler'
  volumes:
    - /var/lib/postgresql/data
    - /bundler
